### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by FedeG** [lelylan/api-proxy#1]
I'll send a PR with the Dockerfile

**Comment by andreareginato** [comment]
Looks great @FedeG, thanks for your contribution. 

Looking at all the pull requests you are making, I was thinking at a solution that could make the deployment fully automated. Do you have any experience with tools like ansible or salt?

**Comment by FedeG** [comment]
I haven't experiences with ansible or salt but i have experience with docker-compose
I'll send a PR with the docker-compose.yml to [lelylan/lelylan](https://github.com/lelylan/lelylan/) for deployment fully automated in the future.

**Comment by andreareginato** [comment]
Great @FedeG! 
I would love to know in which kind of project you are using Lelylan.

Best!
